# Generated by Django 5.0.7 on 2024-07-20 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 21, 2, 48, 3, 168953), verbose_name='date published'),
        ),
    ]
