# Generated by Django 5.0.7 on 2024-07-22 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tutorialcategory_tutorials_tutorial_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 22, 19, 49, 29, 323058), verbose_name='date published'),
        ),
    ]
