# Generated by Django 5.0.7 on 2024-07-22 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tutorials_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 22, 20, 1, 54, 183316), verbose_name='date published'),
        ),
    ]
