# Generated by Django 5.0.7 on 2024-07-22 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_tutorials_tutorial_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialcategory',
            name='category_image',
            field=models.CharField(default=1, max_length=500),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 23, 2, 34, 55, 471603), verbose_name='date published'),
        ),
    ]
