# Generated by Django 5.0.7 on 2024-07-22 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tutorialcategory_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialseries',
            name='series_image',
            field=models.CharField(default=1, max_length=500),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 23, 2, 53, 13, 840966), verbose_name='date published'),
        ),
    ]
