# Generated by Django 5.0.7 on 2024-07-24 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tutorialseries_series_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 24, 16, 38, 32, 749875), verbose_name='date published'),
        ),
    ]
