# Generated by Django 5.0.7 on 2024-07-24 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_tutorials_tutorial_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorials",
            name="tutorial_published",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 24, 19, 26, 41, 118864),
                verbose_name="date published",
            ),
        ),
    ]
