# Generated by Django 5.0.7 on 2024-07-26 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_alter_tutorials_tutorial_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorials",
            name="tutorial_published",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 27, 0, 48, 16, 655763),
                verbose_name="date published",
            ),
        ),
    ]
