# Generated by Django 5.0.7 on 2024-07-26 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_alter_tutorials_tutorial_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorials",
            name="tutorial_published",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 27, 3, 8, 14, 218752),
                verbose_name="date published",
            ),
        ),
    ]
