# Generated by Django 5.0.7 on 2024-07-27 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_alter_tutorials_tutorial_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorials",
            name="tutorial_published",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 27, 20, 4, 44, 814675),
                verbose_name="date published",
            ),
        ),
    ]
